### ISSUE TITLE
LUA Code Error.

### ISSUE THREAD

**Issue by DMNight6** [bruceCzK/Death-is-Not-the-End#1]
There is an error that required to be fixed asap. The error is caused by __add in the lua script

**Comment by DMNight6** [comment]
line:82

**Comment by DMNight6** [comment]
whoops
wrong line
Token_Menu.lua line # 133 tis the correct one

**Comment by DMNight6** [comment]
more detailed,
-----------------------------------------
function: ADDXP2 -- file: Token_Menu.lua line # 133 | MOD: Death Is Not The End
function: onMouseUp -- file: ISContextMenu.lua line # 90 | Vanilla

ERROR: General     , 1681913624864> 559,253,864> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: __add not defined for operands in ADDXP2 at KahluaUtil.fail line:82.
ERROR: General     , 1681913624865> 559,253,865> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: __add not defined for operands in ADDXP2
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:676)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
	at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
	at zombie.ui.UIElement.onMouseUp(UIElement.java:1228)
	at zombie.ui.UIManager.update(UIManager.java:816)
	at zombie.GameWindow.logic(GameWindow.java:262)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1681913624866> 559,253,866> -----------------------------------------
STACK TRACE

**Comment by bruceCzK** [comment]
Hi @DMNight6 , could you make a pull request?

**Comment by DMNight6** [comment]
oh nvm
just missing one thing

**Comment by DMNight6** [comment]
you can close this
mb, wrong code base
